name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python -m pytest

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.AWS_EC2_IP }}
        USER: ${{ secrets.AWS_EC2_USER }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$KEY" > private_key && chmod 600 private_key
        scp -i private_key -o StrictHostKeyChecking=no -r ./* ${USER}@${HOST}:~/app
        ssh -i private_key -o StrictHostKeyChecking=no ${USER}@${HOST} '
          cd ~/app
          pip install -r requirements.txt
          sudo systemctl restart your-fastapi-service
        '
